// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("seedallbeat", "fields.yml", asset.BeatFieldsPri, AssetFieldsYml); err != nil {
		panic(err)
	}
}

// AssetFieldsYml returns asset data.
// This is the base64 encoded gzipped contents of fields.yml.
func AssetFieldsYml() string {
	return "eJxsz89Pq1AQxfE9f8V56aKbFt57S1Yaf8VNY6qJ6wucwujlXsIMVf57I8YqpNvv5HOSWeH5cr+73939wXVEiAZWYrBGFAfxRCU9S/PjBmJ4c4qagb0zVihGWEPcXD2i6+MLS9skKxROWSGGqR/Zq8SAf+n/9G+arPDg6ZQ4ioqhMes0z7JarBmKtIxtRu/UpMxYKixCh7qmGsrGhZpT+pw9CH2laZJs8coxh5KV876gswQwMc9l/CJ5AgBbBNcyx/rCpKWaa7v1dDjZU//OY8cclTPOBiya83P59DtNysdQz1SIw5FueJ/D3aKet4felSYxzO3top635sR77tnFoFz8e+70s/IRAAD//9l0qe4="
}
