// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("seedallbeat", "fields.yml", asset.BeatFieldsPri, AssetFieldsYml); err != nil {
		panic(err)
	}
}

// AssetFieldsYml returns asset data.
// This is the base64 encoded gzipped contents of fields.yml.
func AssetFieldsYml() string {
	return "eJx00c2OlEAUxfE9T3FML2YzQ6tLVhq/4qZjRhPXF+o0XKe6qkLdZuTtzWAcKcTtv/I7yYUDvr+9P30+fXqB9xEhGujUYINmnNUTTkd25udbqOFRMnoGjmJ0aGfYQHx49xVpjD/Y2W11QCuZDjEsfeKYNQa8ql/XL+vqgC+ekolJsxoGs5Sb47FXG65t3cXLkV6yaXdkl2ER+dr3zIZukNBzSU+zZ6V3ua6qOzxwbpBJJ963FDNm01QBpua5//SbNxUA3CHIhQ1u3phemE0u6WZ5eF547n/ynNjAibEYsGjiS/ltnRblY+gLFeJ1olx/lvC0qfv2PEpnGkNpP27qvjVR73nPFEPm5t69p/2VbpyTxZKXbXEPnB/j6Ar69F9KuC7/ZYkcS7YuC9NUCJlEvbR+c+U/ebFtjJ4SigGv08auy/6HcZTNdevy1/wKAAD//7ogC+A="
}
