// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("seedallbeat", "fields.yml", asset.BeatFieldsPri, AssetFieldsYml); err != nil {
		panic(err)
	}
}

// AssetFieldsYml returns asset data.
// This is the base64 encoded gzipped contents of fields.yml.
func AssetFieldsYml() string {
	return "eJx00b+O00AQx/HeTzEoxTV3DlC6AvFPNCd0gKjH3l/s4Ta7q51JIr89OiOC13ba7+ozmYx39Ov90+PXxy+v6GOkEI3gxMgGUTqIBznJ6MyP9yRGF1bqEZDZ4KgdyQbQpw/fKeX4G53dVztqWeEohqmfkVVioDf12/p1Xe3omwcr6CwqRoNZ0ma/78WGU1t38biHZzXp9uiULJKe+h5q1A0cekzpZexB4J3WVfVAzxgbUsCx9wY1SRWRiXms81/WVEREDxT4iIbu3pkcocbHdDc9XPW1/8tjQkOODcUAi8a+lD/maVI+hr5Qh8ydSQwl/Lyo29ZYvMcTUgyKxc5bT9tTujwmiyUv2+SeMV5idgV9uWsJ5+UmS0Au2bxMTFIh+MziufWLf7nKk21j9OBQDBANuJS4SDehl/PiR+dl+6IOvDjLvGybgIuWZl5um/V+y7pto3e63nNZt22Kp9wh2M+0+Iqr/t//CQAA//+6cEtE"
}
