// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("seedallbeat", "fields.yml", asset.BeatFieldsPri, AssetFieldsYml); err != nil {
		panic(err)
	}
}

// AssetFieldsYml returns asset data.
// This is the base64 encoded gzipped contents of fields.yml.
func AssetFieldsYml() string {
	return "eJx00s9u1DAQx/F7nmLQHnpps8AxJxD/xKVCpYjzJP5tMtRrW5nZXeXtUYNo48R7/VofezLKjn5/fLj/fv/tDX2OFKIRnBjZIEoH8SAnIzrz0y2J0YWVegSMbHDUTmQD6Munn5TG+Aed3VY7alnhKIa5nzGqxEDv6vf127ra0Q8PVtBZVIwGs6TNft+LDae27uJxD89q0u3RKVkkPfU91KgbOPSY0/O1B4F3WlfVHT1hakgBx94b1CRVRCbmsc3/WFMREd1R4CMauvlgcoQaH9PNfPCiX/r/PCU05NiQXWDR2OfycZlm5WPoM3UYuTOJIYdfV7VsjcV7PCDFoFjNXDoq39KNU7KY87zN7gnTJY4uo897zeGyXGUJGHO2LDOTlAk+s3hu/eorN3m2bYweHAqreoRaaU/LXl6SaMAlp1m6+rCX82roZSk/5sCrtS5L2QRcNDfLct1s51vXso3e6XbOdS3bFE9jh2C/0uov2PRX/zcAAP//MfZeKA=="
}
