// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("seedallbeat", "fields.yml", asset.BeatFieldsPri, AssetFieldsYml); err != nil {
		panic(err)
	}
}

// AssetFieldsYml returns asset data.
// This is the base64 encoded gzipped contents of fields.yml.
func AssetFieldsYml() string {
	return "eJyEk09vEzEQxc/spxiUQy9tAhxzApU/6qVUTYFj5dgvm6GOx7InifbboyxKWDsbev1Zv+fZ59kJ/fr0eH93/+0tfRYKogTHSrrmTCv2IMcJVn13Tay0N5laBCSjcLTsSNegL7cLikl+w+p1M6GlyXAkoec7pMwS6P30w/TdtJnQg4fJoB1nVlqrxjyfzVrW9XY5tbKZwZusbGewmVQob9sWWcmuTWjRo0PsiuFdnjbNDb2gm1MGnPFekZVjQ6SsHuf4rzZviIhuKJgN5nT1UXmDrGYTr/qDk33iR9xFzMkZRRGgosaX5tMQ9ZaX0BbWKhmrLKEUv1Z03FXD3uMRUUJGNfPY0XiKTV1UKfWS9d4Lur0kV6iHXktxSC5qEUilNiS9xrEwzM6wN0tffeUZ7t2liIcJI1U9IetYT0M+XhLngH2pFujixZ531dBDMn6Zg6lqHZJxJ2CfS2dILjvn89V03BXv8vmcNR13o2yTRdAfsdqCMz7qv2khUThUT9lCvFhz+G1IVv1KHdfomNRCnv+Zx3GOcc9VgQtNHFpKiAkZQU/RZcz/Nt2ydmXoz8O+ve7JNmiq1AfT5VdNzmLFVU96Kw50t/hO8VLEnwAAAP//7c/H2w=="
}
